package client.zt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-07-05T13:39:43.801+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "BonusReqResourceImplService", 
                  wsdlLocation = "http://localhost:8080/kasly-mobile/service/bonusReqResource?wsdl",
                  targetNamespace = "http://impl.soap.bonus.kasly.com/") 
public class BonusReqResourceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.soap.bonus.kasly.com/", "BonusReqResourceImplService");
    public final static QName BonusReqResourceImplPort = new QName("http://impl.soap.bonus.kasly.com/", "BonusReqResourceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/kasly-mobile/service/bonusReqResource?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BonusReqResourceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/kasly-mobile/service/bonusReqResource?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BonusReqResourceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BonusReqResourceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BonusReqResourceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BonusReqResourceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BonusReqResourceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BonusReqResourceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IBonusReqResource
     */
    @WebEndpoint(name = "BonusReqResourceImplPort")
    public IBonusReqResource getBonusReqResourceImplPort() {
        return super.getPort(BonusReqResourceImplPort, IBonusReqResource.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBonusReqResource
     */
    @WebEndpoint(name = "BonusReqResourceImplPort")
    public IBonusReqResource getBonusReqResourceImplPort(WebServiceFeature... features) {
        return super.getPort(BonusReqResourceImplPort, IBonusReqResource.class, features);
    }

}
